# Generated by Django 5.2.3 on 2025-06-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_alter_user_id_listing_comment_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="bid",
            new_name="user_bid",
        ),
    ]
