# Generated by Django 5.2.3 on 2025-07-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0002_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.CharField(
                blank=True, default="Hey there! I am using Messenger.", max_length=255
            ),
        ),
    ]
