# Generated by Django 5.2.3 on 2025-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0003_alter_user_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
    ]
