# Generated by Django 5.2.3 on 2025-07-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0004_chat_is_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
